    SELECT B.VENDOR_ID, C.NAME1, A.DESCR, A.FISCAL_YEAR, A.FUND_CODE, A.PROGRAM_CODE, A.ACCOUNT, A.OPERATING_UNIT,
            A.DEPTID, A.PROJECT_ID, A.BUSINESS_UNIT_PC, SUM(A.MONETARY_AMOUNT)
        FROM PS_VCHR_ACCT_DRILL A, PS_VOUCHER B, PS_VENDOR C
        WHERE ( A.BUSINESS_UNIT = B.BUSINESS_UNIT
            AND A.VOUCHER_ID = B.VOUCHER_ID
            AND B.VENDOR_SETID = C.SETID
            AND B.VENDOR_ID = C.VENDOR_ID
            AND B.BUSINESS_UNIT = 'KERNH'
            AND A.DST_ACCT_TYPE = 'DST'
            AND B.POST_STATUS_AP = 'P'
            AND A.DEPTID = ?
            AND A.FISCAL_YEAR = ?)
        GROUP BY
            B.VENDOR_ID, C.NAME1, A.DESCR, A.FUND_CODE, A.PROGRAM_CODE, A.ACCOUNT, A.DEPTID, A.BUSINESS_UNIT_PC, A.PROJECT_ID, A.ACCOUNTING_PERIOD, 
            A.FISCAL_YEAR, A.OPERATING_UNIT
        ORDER BY SUM(A.MONETARY_AMOUNT) DESC